DEPARTMENTS = [
    "Arts",
    "Biodiscovery Institute",
    "Biosciences",
    "Bio-Support Unit",
    "Campaign and Alumni Relations Office",
    "Catering, Conferences & Hospitality",
    "CDO Office",
    "Chemistry",
    "Chief Financial Officer's Office",
    "Commercial",
    "Computer Science",
    "Cultures, Languages & Area Studies",
    "Dean's Office (M&HS)",
    "Deputy Registrars",
    "Digital Research",
    "Digital Research Service",
    "Directorate",
    "DTS Architecture",
    "DTS Service Delivery",
    "DTS Service Design",
    "Economics",
    "Education",
    "Engineering",
    "English",
    "External Relations",
    "Financial Control",
    "Financial Management",
    "Geography",
    "Getting in Shape",
    "Governance and Assurance Central",
    "Health Sciences",
    "HR Business Partnering Policy & Projects",
    "HR Digital Systems & Services",
    "HR Senior Leadership Team",
    "Humanities",
    "Internal Audit Service",
    "Law",
    "Life Sciences",
    "Mathematical Sciences",
    "Medicine",
    "Nottingham Hospitality - BI Dummy",
    "Nottingham University Business School",
    "Operations",
    "Organisational & People Development",
    "Pharmacy",
    "Physics & Astronomy",
    "Planning, Performance & Strategic Change",
    "Politics and International Relations",
    "Psychology",
    "Registrar's Office",
    "Research and Innovation",
    "Science",
    "Social Sciences",
    "Sociology & Social Policy",
    "Students Union",
    "Sustainability & Development",
    "UNIP",
    "University of Nottingham Libraries",
    "Veterinary Medicine & Science",
    "Vice-Chancellor's Office"
]
